Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/objects/Apex_Sharing_Test__c.object
<CustomObject>
    <description>Object to test Apex Sharing</description>
    <fields>
        <fullName>instanceName__c</fullName>
        <label>instanceName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ApexShare</label>
    <nameField>
        <label>Test Apex Sharing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApexShares</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/classes/ApexSecuTestHandler.cls
public  class ApexSecuTestHandler
{
    public ApexSecuTestHandler(){}
    public void beforeInsert(Apex_Sharing_Test__c[] atObj)
    {
		for (Apex_Sharing_Test__c atc : atObj)
        {
            Schema.DescribeFieldResult F = Apex_Sharing_Test__c.instanceName__c.getDescribe();
            if (F.isUpdateable())
                {
  			          atc.instanceName__c = atc.instanceName__c + 'UUUUUAA';        
                }    
            else                
            	atc.instanceName__c = atc.instanceName__c + 'BAA';
        }
    }
}