Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions.</description>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/objects/Interview__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Interview_Time__c</fullName>
        <label>Interview Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Candidates</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Scheduled_Window__c</fullName>
        <label>Scheduled Window</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Interview</label>
    <nameField>
        <displayFormat>Interview-{0000}</displayFormat>
        <label>Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/objects/Position__c.object
<CustomObject>
    <description>This object stores information about the open job positions at our company.</description>
    <fields>
        <fullName>Max_Pay__c</fullName>
        <label>Max Pay</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Pay__c</fullName>
        <label>Min Pay</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/classes/TestInterview.cls
@isTest
private class TestInterview {

    static testMethod void myUnitTest() {
        Candidate__c c = new Candidate__c(Name = 'Test', Email__c = 'test@gmail.com');
        Insert c;
        Position__c p = new Position__c(Name = 'Test', Min_Pay__c = 100, Max_Pay__c = 1000);
        Insert p;
        Interview__c interview = new Interview__c(Candidate__c = c.id, Position__c = p.id, Interview_Time__c = DateTime.now(), Scheduled_Window__c = 30);
        insert interview;
       
        System.assert(interview.Title__c != '');
    }

}