Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions.</description>
    <label>Candidate</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/objects/Interview__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Interview_Time__c</fullName>
        <label>Interview Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Candidates</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Interview</label>
    <nameField>
        <displayFormat>Interview-{0000}</displayFormat>
        <label>Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/objects/Position__c.object
<CustomObject>
    <description>This object stores information about the open job positions at our company.</description>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/classes/myInterviews.cls
public class myInterviews {

        public List <Interview__c> interviewList= new List <Interview__c>();
        public String selectedTimeItem{get;set;}
        public String selectedPosition{get;set;}

        public List <Interview__c> getInterviewList(){
            return interviewList;
        }

        public void setTimeItem(String selectedTimeItem) {
            this.selectedTimeItem = selectedTimeItem;
        }
        
        public void setSelectedPosition(String selectedPosition) {
            this.selectedPosition = selectedPosition;
        }        

public PageReference filterResults(){

    if (selectedTimeItem=='Today'){
                 if (selectedPosition == 'Filter by Position...'){
                     interviewList = [SELECT Title__c, Name, Candidate__r.Name, Position__r.Name, Interview_Time__c from Interview__c WHERE Interview_Time__c=TODAY];
                 }
                 else{
                     interviewList = [SELECT Title__c, Name, Candidate__r.Name, Position__r.Name, Interview_Time__c from Interview__c WHERE Interview_Time__c=TODAY AND Position__r.Name=:selectedPosition];
                 }    }
    else if (selectedTimeItem=='Tomorrow'){
                 if (selectedPosition == 'Filter by Position...'){
                     interviewList = [SELECT Title__c, Name, Candidate__r.Name, Position__r.Name, Interview_Time__c from Interview__c WHERE Interview_Time__c=TOMORROW];
                 }
                 else{
                     interviewList = [SELECT Title__c, Name, Candidate__r.Name, Position__r.Name, Interview_Time__c from Interview__c WHERE Interview_Time__c=TOMORROW AND Position__r.Name=:selectedPosition];
                 }
    }
    else if (selectedTimeItem=='This Week'){
                 if (selectedPosition == 'Filter by Position...'){
                     interviewList = [SELECT Title__c, Name, Candidate__r.Name, Position__r.Name, Interview_Time__c from Interview__c WHERE Interview_Time__c=THIS_WEEK];
                 }
                 else{
                     interviewList = [SELECT Title__c, Name, Candidate__r.Name, Position__r.Name, Interview_Time__c from Interview__c WHERE Interview_Time__c=THIS_WEEK AND Position__r.Name=:selectedPosition];
                 }    } 
    else if (selectedTimeItem=='All Time'){
                 if (selectedPosition == 'Filter by Position...'){
                     interviewList = [SELECT Title__c, Name, Candidate__r.Name, Position__r.Name, Interview_Time__c from Interview__c WHERE Interview_Time__c>=TODAY];
                 }
                 else{
                     interviewList = [SELECT Title__c, Name, Candidate__r.Name, Position__r.Name, Interview_Time__c from Interview__c WHERE Interview_Time__c>=TODAY AND Position__r.Name=:selectedPosition];
                 }    }        
    else
    {
    interviewList = [SELECT Title__c, Name, Candidate__r.Name, Position__r.Name, Interview_Time__c from Interview__c WHERE Interview_Time__c=TODAY];
    }
    
    return null;
}


    public void go(){
         
    }
    
    public List<SelectOption> getItems() {
       List <SelectOption> options = new List <SelectOption>();
        
        List <Position__c> listOfPositions = new List <Position__c>();
        listOfPositions = [SELECT Name from Position__c];
        
            options.add(new SelectOption('Filter by Position...','Filter by Position...'));
        
        for(Position__c p: listOfPositions){
        
            options.add(new SelectOption(p.Name,p.Name));
        }
        
        return options;
    }
    
       public List<SelectOption> getTimeItems() {
       List <SelectOption> options = new List <SelectOption>();
        
       options.add(new SelectOption('Today','Today'));
       options.add(new SelectOption('Tomorrow','Tomorrow'));
       options.add(new SelectOption('This Week','This Week'));
       options.add(new SelectOption('All Time','All Time'));
       

        return options;
    }
   
    
}