Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions.</description>
    <label>Candidate</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/objects/Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Feedback__c</fullName>
        <label>Feedback</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Interview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interview</label>
        <referenceTo>Interview__c</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Fit for role</label>
        <picklist>
            <picklistValues>
                <fullName>Bad Fit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OK Fit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good Fit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Great Fit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perfect Fit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rating_out_of_10__c</fullName>
        <label>Rating out of 10</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Feedback</label>
    <nameField>
        <displayFormat>Feedback-{000}</displayFormat>
        <label>Feedback No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/objects/Interview__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Feedback__c</fullName>
        <description>Provide feedback on candidate</description>
        <inlineHelpText>Provide feedback</inlineHelpText>
        <label>Feedback</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Interview_Time__c</fullName>
        <label>Interview Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Candidates</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Scheduled_Window__c</fullName>
        <label>Scheduled Window</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Interview</label>
    <nameField>
        <displayFormat>Interview-{0000}</displayFormat>
        <label>Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/objects/Position__c.object
<CustomObject>
    <description>This object stores information about the open job positions at our company.</description>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/classes/demoReset.cls
public class demoReset {
    public List <Interview__c> interviewList = new List <Interview__c>();
    public Boolean demoReset = false;
    
    public Boolean getDemoReset(){
        return demoReset;
    }
    
    public void go(){
            interviewList = [SELECT id FROM Interview__c];
            if (interviewList.size() > 0){
                  delete interviewList;

            }
            
            Datetime currentDateTime = System.now();
            DateTime firstTime = currentDateTime.addHours(1);  
            DateTime secondTime = currentDateTime.addHours(2);
            DateTime thirdTime = currentDateTime.addHours(3);    
                    
            DateTime fourthTime = currentDateTime.addHours(1);            
            fourthTime = fourthTime.addDays(1);            

            DateTime fifthTime = currentDateTime.addHours(2);            
            fifthTime = fifthTime.addDays(1);  
            
            DateTime sixthTime = currentDateTime.addHours(2);            
            sixthTime = sixthTime.addDays(1);                                    
                
            Interview__c firstInterview = new Interview__c(Candidate__c = 'a1jE00000002BVc', Position__c = 'a1mE0000000jT7D', Interview_Time__c = firstTime, Scheduled_Window__c = 45);
            insert firstInterview;

            Interview__c secondInterview = new Interview__c(Candidate__c = 'a1jE00000002BVX', Position__c = 'a1mE0000000jT7E', Interview_Time__c = secondTime, Scheduled_Window__c = 45);
            insert secondInterview;  
            
            Interview__c thirdInterview = new Interview__c(Candidate__c = 'a1jE000000021rY', Position__c = 'a1mE0000000sa5l', Interview_Time__c = thirdTime, Scheduled_Window__c = 45);
            insert thirdInterview; 
            
            Interview__c fourthInterview = new Interview__c(Candidate__c = 'a1jE000000021rT', Position__c = 'a1mE0000000jT7D', Interview_Time__c = fourthTime, Scheduled_Window__c = 45);
            insert fourthInterview;  
            
            Interview__c fifthInterview = new Interview__c(Candidate__c = 'a1jE00000001tSK', Position__c = 'a1mE0000000jT7E', Interview_Time__c = fifthTime, Scheduled_Window__c = 45);
            insert fifthInterview;     
            
            Interview__c sixthInterview = new Interview__c(Candidate__c = 'a1jE00000001tSK', Position__c = 'a1mE0000000jT7D', Interview_Time__c = sixthTime, Scheduled_Window__c = 45);
            insert sixthInterview;                                            

            Feedback__c firstFeedback = new Feedback__c(Interview__c = firstInterview.id, Rating__c = 'Good Fit', Rating_Out_Of_10__c = 5);
            Feedback__c secondFeedback = new Feedback__c(Interview__c = fourthInterview.id, Rating__c = 'Bad Fit', Rating_Out_Of_10__c = 3);
            Feedback__c thirdFeedback = new Feedback__c(Interview__c = sixthInterview.id, Rating__c = 'Good Fit', Rating_Out_Of_10__c = 6);
            
            insert firstFeedback;
            insert secondFeedback;
            insert thirdFeedback;
            
            demoReset = true;
    }
    
    
}