Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/objects/iOrder__c.object
<CustomObject>
    <fields>
        <fullName>Order_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Order_External_ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order_Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>iOrder</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>iOrders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/classes/iOrderControllerExtension.cls
public with sharing class iOrderControllerExtension {

	private iOrder__c myOrder;
	OrderShipInfo myOrderShipInfo;
	OrderShipInfo.ShipInfo theShipInfo;

	private ApexPages.StandardController controller {get;set;}

	public iOrderControllerExtension(ApexPages.StandardController controller) {
		this.controller = controller;
		this.myOrder = (iOrder__c)controller.getRecord();
	}

	public void refreshOrderShipInfo() {
		myOrderShipInfo = new OrderShipInfo();
		theShipInfo = myOrderShipInfo.getOrderShipInfo(this.myOrder.Order_External_ID__c);
		myOrder.Order_Status__c = theShipInfo.status;
		myOrder.Order_External_ID__c = theShipInfo.id;


		System.debug('APEX BADGE Return Status is '+theShipInfo); 
		update myOrder;
	}

	public String getOrderStatus()  
   {  
    return theShipInfo.status;  
   }  
   public String getOrderComments()  
   {  
     return theShipInfo.comments;  
   }  
   public String getOrderOwner()  
   {  
     return theShipInfo.orderOwner;  
   }  
}