Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/objects/Ticker_Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Ticker Item</label>
    <nameField>
        <displayFormat>TI-{00000}</displayFormat>
        <label>Ticker Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticker Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/objects/Ticker_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ticker Settings</label>
    <nameField>
        <label>Ticker Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticker Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Documents/MetaDataIO/MetadataIO-distr-33.0.3-bin/repos/src/classes/TickerDisplayController.cls
public with sharing class TickerDisplayController {
	
	public List<Ticker_Item__c> tickerItems {get;set;}
	public String background {get;set;}
	public String subject {get;set;}
	public String description {get;set;}
	
	public TickerDisplayController() {
		tickerItems = [SELECT Id, Subject__c, Description__c,URL__c FROM Ticker_Item__c];	
		List<Ticker_Settings__c > tickersettings = [SELECT Name, Value__c FROM Ticker_Settings__c];
		
		for(Ticker_Settings__c ts : tickersettings){
			if(ts.Name == 'Subject Color'){
				subject = ts.Value__c;
			}
			if(ts.Name == 'Background Color'){
				background = ts.Value__c;
			}
			if(ts.Name == 'Description Color'){
				description = ts.Value__c;
			}
		}
		
	}

}